#!/bin/bash
# This script is included as a daemon plist file.
# It popups a message dialog, and speak out a reminder, 
# when the battery drops below 40 pct or above 80 pct.
# The battery is longer lasting when charged between (40,80) according to science.


# battery remaining (mAh)
for i in `seq 1 2`
do
  br[i]=$(system_profiler SPPowerDataType | awk '/Charge Remaining/ {print $4}')
  if [ $i -eq 1 ]; then sleep 62s; fi # 62s is a safe pause to get the next battery read
                                      # sleep has units of seconds/minutes/hours/days s/m/h/d 
  #echo ${br[*]}
done

# battery full capacity (mAh)
bf=$(system_profiler SPPowerDataType | awk '/Full Charge Capacity/ {print $5}')

# battery remaining (%)
bp=$((br[2] * 100 / bf))
echo $bp
# if battery pct falls in (15,40) and if battery is still decreasing or
#                         (80,90)                         increasing 
if [[ $bp -ge 15 && $bp -le 40 && br[2] -lt br[1] || 
      $bp -ge 80 && $bp -le 90 && br[2] -gt br[1] ]]
then
# display dialog and giving up after 2 seconds
   osascript -e 'tell app "System Events" to display dialog "battery life: '$bp' %" giving up after 1.5'
# press 'ok' button with no delay
# osascript -e 'tell app "System Events" to display dialog "'$battpct' percent"'
# say battery is low or high
  if [ $bp -ge 80 ]
  then
    say -v Zarvox  "whoever hears this, please unplug this computer now"
    #osascript -e 'say "whoever hears this, please unplug this computer now"'
  else
    say -v Vicki "whoever hears this, please charge this computer now"
    #osascript -e 'say "whoever hears this, please charge this computer now"'
  fi
fi
