#!/bin/bash
# this script is included as a daemon plist file, which shows a message dialog 
# when the battery drops below 40 pct or above 80 pct

# remaining battery charge (mAh)
batterymAh=$(system_profiler SPPowerDataType | awk '/Charge Remaining/ {print $4}')

# full battery capacity (mAh)
totalBatterymAh=$(system_profiler SPPowerDataType | awk '/Full Charge Capacity/ {print $5}')

# remaining battery charge (%)
battpct=$((batterymAh * 100 / totalBatterymAh))

# if battery amp percentage drops in 15<=b<=40 or 80<=b<=90 pct, then prompt the message diaglog for 2 seconds
if [[ $battpct -ge 15 && $battpct -le 40 || 
      $battpct -ge 80 && $battpct -le 90 ]]
then
# display dialog and giving up after 2 seconds
   osascript -e 'tell app "System Events" to display dialog "battery life: '$battpct' %" giving up after 1.5'
# press 'ok' button with no delay
# osascript -e 'tell app "System Events" to display dialog "'$battpct' percent"'
# say battery is low or high
  if [ $battpct -ge 80 ]
  then
    osascript -e 'say " whoever hears this, please unplug this computer now "'
  else
    osascript -e 'say " whoever hears this, please charge this computer now "'
  fi
#c sleec has units of seconds/minutes/hours/days s/m/h/d 
#   sleep 2s
fi
